<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
 /** Delcared Constant Values **/
	const CASUAL_LEAVE = "Casual";
	const SICK_LEAVE = "Sick";
	const LOSS_OF_PAY = "Loss of Pay";
	const ONSITE_LEAVE = "On Site";	
	const PRIVILEGE_LEAVE = "Privilege";
	const PL_CARRIED_OVER = "PL - Carried over";

?>



<?php echo $this->form->id; 
		echo $this->form->user_id;
		?>
<?php 
$leave_limit = $this->form->leave_limit->getValue();
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Leave Limit',(!empty($leave_limit))?$this->form->leave_limit->getValue():"...",'Year',(!empty($this->data['alloted_year']))?$this->data['alloted_year']:"...");
sapp_Helper::viewFooter();
?>
			<div class="clearall usedleaves">
				Used Leaves : <?php echo $this->form->used_leaves->getValue();
				?>				
			</div>
			
			<div class="clearall leavenames">
			<table class="leave-table">
				<thead>
					<tr>
						<th>Leave Type</th>
						<th>Leave Entitled (Days)</th>
						<th>Leave Taken (Days)</th>
						<th>Leave Balance (Days)</th>
					</tr>
				</thead>
				<tbody>
					<?php 						
						if(!empty($this->leaveTypeCount))
						{  
							foreach($this->leaveTypeCount as $key => $leave)							
							{?>				
																	
									<tr>
										<td><?php echo $leave['leavetype']?></td>
										<td>
											<?php 
												if ($leave['leavetype'] == CASUAL_LEAVE){ echo $this->casualType; } 
												if ($leave['leavetype'] == SICK_LEAVE){	echo $this->sickType; } 
												if ($leave['leavetype'] == LOSS_OF_PAY){ echo $this->PlType; }
												if ($leave['leavetype'] == PRIVILEGE_LEAVE){ echo $this->PlCarriedOverType; }  
												if ($leave['leavetype'] == PL_CARRIED_OVER){ echo $this->lossOfPayType; }  
												if ($leave['leavetype'] == ONSITE_LEAVE){ echo $this->onSiteType; }
												?>
										</td>
										<td><?php 
											echo $leave['count'];
										?></td>
										<td>
											<?php										
												if ($leave['leavetype'] == CASUAL_LEAVE){ echo ($this->casualType - $leave['count']); } 
												if ($leave['leavetype'] == SICK_LEAVE){	echo ($this->sickType - $leave['count']); } 
												if ($leave['leavetype'] == LOSS_OF_PAY){ echo ($this->PlType - $leave['count']); }
												if ($leave['leavetype'] == PRIVILEGE_LEAVE){ echo ($this->PlCarriedOverType - $leave['count']); }  
												if ($leave['leavetype'] == PL_CARRIED_OVER){ echo ($this->lossOfPayType - $leave['count']); }  
												if ($leave['leavetype'] == ONSITE_LEAVE){ echo ($this->onSiteType - $leave['count']); }
												?>
										</td>
									</tr>													 						 													
			   			<?php
						    }
						} ?>
				</tbody>
				</table>
			</div>

        <div class="new-form-ui-submit" id="formSubmit">
         <input onclick="closeiframepopup('empleaves','cancel');" type="button" value="Close"  />
       		

</div>