<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/

/**Leave Module for showing all allotted leaves, leave taken and leave balance in a Leave table**/

echo $this->form->id; 
echo $this->form->user_id;

$leave_limit = $this->form->leave_limit->getValue();
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Leave Limit',(!empty($leave_limit))?$this->form->leave_limit->getValue():"...",'Year',(!empty($this->data['alloted_year']))?$this->data['alloted_year']:"...");
sapp_Helper::viewFooter();
?>
			<div class="clearall usedleaves">
				Used Leaves : <?php echo $this->form->used_leaves->getValue(); ?>				
			</div>
			
			<div class="clearall leavenames">			
			<table class="leave-table">
				<thead>
					<tr>
						<th>Leave Type</th>
						<th>Leave Entitled (Days)</th>
						<th>Leave Taken (Days)</th>
						<th>Leave Balance (Days)</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				$leaveTakenValue = $this->leaveTypeCount;																													
				foreach($this->allotedLeaves as $key => $leaveAllot) { 
				?>																					
					<tr>
						<td>
							<?php 
								echo $leaveAllot['leavetype']; 
							?>
						</td>
						<td>
							<?php 
								$leaveEntitled = $leaveAllot['no_of_days_allotted'];
								echo $leaveEntitled;																						
							?>
						</td>										
						<td>
							<?php																
								$leaveBalance = true;	
								$leaveTaken = true;																										
								foreach ($leaveTakenValue as $key => $leaveTakenColumn) {													 													
									if($leaveTakenColumn['leavetype'] == $leaveAllot['leavetype']) {
										$leaveTaken = $leaveTakenColumn['count'];
										echo $leaveTaken;						
										if($leaveTaken != 0) 
											$leaveBalance = $leaveEntitled - $leaveTaken;																																																					
									} 
								}
								if($leaveTaken)
									echo 0;											
							?>
						</td>
						<td>
							<?php 
								if($leaveBalance)
									echo $leaveEntitled;
								else
									echo $leaveBalance;											 																														
							?>
						</td>
					</tr>													 						 													
					<?php 
						} 
					?>										
				</tbody>
				</table>
			</div>
        <div class="new-form-ui-submit" id="formSubmit">
         <input onclick="closeiframepopup('empleaves','cancel');" type="button" value="Close"  />       		
</div>